# Generated by Django 2.1.7 on 2019-03-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='professional',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='agenda.Professional'),
        ),
    ]
