# Generated by Django 2.1.7 on 2019-03-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_professional_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='professional',
        ),
        migrations.AddField(
            model_name='agenda',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='agenda.Business'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
