# Generated by Django 2.1.7 on 2019-03-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='atendimento',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='agenda.Agenda'),
        ),
    ]
