# Generated by Django 2.1.7 on 2019-03-04 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_auto_20190304_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
